### ISSUE TITLE
Configurable option: alwaysShowOutput

### ISSUE THREAD

**Issue by andywer** [SamVerschueren/listr-verbose-renderer#1]
Sorry for opening issues here and there, but what do you think about having an `alwaysShowOutput` (or similar) option?

Could be very useful in debugging and/or CI scenarios where you might want to have all the output available.

Currently the Renderer class doesn't really have a way to pass options. I would suppose you pass the options to the constructor. One could either configure a renderer instance and pass it to `listr` or `listr` passes down the Listr instance's options to the renderer and we configure the renderer by configuring the listr.

Cheers!

**Comment by SamVerschueren** [comment]
Doesn't it render all the output then? That was the goal of this renderer :p.

> Currently the Renderer class doesn't really have a way to pass options.

Yes it does. The second argument in the constructor accepts the same options as provided to the `Listr` object. See the [docs](https://github.com/SamVerschueren/listr#custom-renderers).

The update renderer has [options](https://github.com/SamVerschueren/listr-update-renderer#options) for example.

**Comment by andywer** [comment]
My bad, didn't see the options in the doc 😉

No, I am pretty sure it rendered the status changes of every task/subtask, but not it's output (stdout) (except for an error occuring). It's nice that it's usually hidden, but sometimes you want to see everything.

**Comment by SamVerschueren** [comment]
Ok, this is a bug then. It should render everything, including stdout. Have to investigate as I don't see a reason why it's not working. Care to provide a minimal test example? Would help debugging it and make sure I understand the problem correctly :).

**Comment by andywer** [comment]
See here: https://gist.github.com/andywer/cbaca0ebb1a8d5e72279e3bfb09019fa

If you have to touch it anyway... Could you make "always printing the whole output" optional? 😅

Use case:
If I pipe the output to a file I usually don't want to see all the output. I just need to get rid of the fancy animation, so my log file won't contain a million control characters.
When I am debugging I might like to have all the output, though.

**Comment by andywer** [comment]
Any news on this?

**Comment by SamVerschueren** [comment]
Sorry, didn't find the time to look into this.

> I just need to get rid of the fancy animation

The verbose renderer doesn't have an animation.

**Comment by andywer** [comment]
@SamVerschueren The "I just need to get rid of the fancy animation" was just the explanation why I use the verbose renderer at all 😉

My point was: Would be nice to have this renderer to get plain text output and set an option to switch between verbose output and "only output on error" (but plain text, without animations)

**Comment by SamVerschueren** [comment]
> Would be nice to have this renderer to get plain text output

Yes, I've been playing with the idea of either adding an option to strip the ANSI escape codes or just don't add them to start with. Although I can see the extra benefit of having some pretty colors in the terminal output when using the verbose renderer. Instead, let's just detect if we are running in a tty and adjust the output accordingly.

> only output on error

Seems a use case for another renderer which could extend this one.

**Comment by andywer** [comment]
Sure!

FYI: I tried some methods to detect whether in a TTY environment or not for npm-launch. After trying `require('tty').isatty` (didn't work very well) I finally decided to go with `process.stdout.isTTY`. Might be a good idea to check for `process.env.CI`, too.

**Comment by SamVerschueren** [comment]
If I'm not mistaken `process.stdout.isTTY` is not enough and you had to check for something extra, can't remember what it was though. @sindresorhus, can you enlighten me :)?

**Comment by sindresorhus** [comment]
@SamVerschueren Weird, `chalk` should already handle that through the [`supports-color`](https://github.com/chalk/supports-color) module.

**Comment by SamVerschueren** [comment]
@sindresorhus  Oh cool, didn't know that and I must say I didn't tested it either.

**Comment by SamVerschueren** [comment]
@andywer Sorry for keeping this open for such a long time. I'm working on Listr and bumped into this issue so I started investigating this. If you want to show the output generated in `execa.shell`, you have to set the `stdio` property to `inherit`.

```js
const rootListr = createListr([
  {
    title: 'root',
    task: () => createListr([
      {
        title: 'sleep 1s',
        task: () => execa.shell('echo "Sleeping 1s" && sleep 1 && echo "Done sleeping"', {stdio: 'inherit'})
      },
      {
        title: 'sleep 2s',
        task: () => execa.shell('sleep 2')
      }
    ])
  }
])

rootListr.run().catch((error) => {
  console.error(error)
})

function createListr (tasks) {
  return new Listr(tasks, { renderer: 'verbose' })
}
```

This however generates the following output

> [09:02:53] root [started]
> [09:02:53] sleep 1s [started]
> Sleeping 1s
> Done sleeping
> [09:02:54] sleep 1s [completed]
> [09:02:54] sleep 2s [started]
> [09:02:56] sleep 2s [completed]
> [09:02:56] root [completed]

As you can see, you don't have any timestamp at when the logs happened. If you want that, you can check how we do it in `np`. We wrote a little wrapper around `execa` which creates an Observable stream for stdout and stderr. You can see the code over [here](https://github.com/sindresorhus/np/blob/master/index.js#L14-L22). I'm going to extract this in a seperate library, seems like a good idea.

```js
'use strict';
const execa = require('execa')
const Listr = require('listr')
const split = require('split');
const Observable = require('rxjs').Observable;
const streamToObservable = require('stream-to-observable');

const exec = (cmd) => {
	// Use `Observable` support if merged https://github.com/sindresorhus/execa/pull/26
	const cp = execa.shell(cmd);

	return Observable.merge(
		streamToObservable(cp.stdout.pipe(split()), {await: cp}),
		streamToObservable(cp.stderr.pipe(split()), {await: cp})
	).filter(Boolean);
};

const rootListr = createListr([
  {
    title: 'root',
    task: () => createListr([
      {
        title: 'sleep 1s',
        task: () => exec('echo "Sleeping 1s" && sleep 1 && echo "Done sleeping"')
      },
      {
        title: 'sleep 2s',
        task: () => exec('sleep 2')
      }
    ])
  }
])

rootListr.run().catch((error) => {
  console.error(error)
})

function createListr (tasks) {
  return new Listr(tasks, { renderer: 'verbose' })
}
```

If you use the code above, it will output like this

> [09:09:16] root [started]
> [09:09:16] sleep 1s [started]
> [09:09:16] → Sleeping 1s
> [09:09:17] → Done sleeping
> [09:09:17] sleep 1s [completed]
> [09:09:17] sleep 2s [started]
> [09:09:19] sleep 2s [completed]
> [09:09:19] root [completed]

Hope this answers your question, if it doesn't let me know. And again, sorry for the late reply.
