### ISSUE TITLE
Rendering without the timestamp

### ISSUE THREAD

**Issue by Arhane** [SamVerschueren/listr-verbose-renderer#4]
There is a problem when testing is neeeded.

I assert the output through [jest snapshots](https://facebook.github.io/jest/docs/en/snapshot-testing.html#content). And when there is a timestamp in snapshot, the snapshots are always different.

![Diff between a snapshot and a real output](http://dl4.joxi.net/drive/2017/10/20/0020/0140/1372300/00/3a8ff94094.jpg)

I suggest to add an option when there is no timestamp in the console output

**Comment by SamVerschueren** [comment]
You could've worked around it by providing an space to the `dateFormat` option :). Not ideally, I know. That's why you can now set `dateFormat: false` and it will hide the timestamp entirely. Just reinstall `Listr` and it will automatically pick up the latest verbose renderer.
